# DISK_SIZE = '50GB'
# MEMORY = "1250"

Vagrant.configure("2") do |config|
  config.vm.box = "base"

# if a specific disk size is desired, run a script to provision each box to format the filesystem
# config.vm.provision "shell", path: "disk-extend.sh"

# required: run a script to disable swap on each virtual machine
  config.vm.provision "shell", path: "disable-swap.sh"

  config.vm.define "c1-cp1" do |c1cp1|
    c1cp1.vm.box = "bento/ubuntu-18.04"
    # c1cp1.disksize.size = DISK_SIZE
    c1cp1.vm.network "private_network", ip: "172.16.94.10"
    c1cp1.vm.hostname = "c1-cp1"
    c1cp1.vm.provider "virtualbox" do |vb|
      # vb.memory = MEMORY
      vb.cpus = "2"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end

  config.vm.define "c1-node1" do |c1node1|
    c1node1.vm.box = "bento/ubuntu-18.04"
    # c1node1.disksize.size = DISK_SIZE
    c1node1.vm.network "private_network", ip: "172.16.94.11"
    c1node1.vm.hostname = "c1-node1"
    c1node1.vm.provider "virtualbox" do |vb|
      # vb.memory = MEMORY
      vb.cpus = "2"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end

  config.vm.define "c1-node2" do |c1node2|
    c1node2.vm.box = "bento/ubuntu-18.04"
    # c1node2.disksize.size = DISK_SIZE
    c1node2.vm.network "private_network", ip: "172.16.94.12"
    c1node2.vm.hostname = "c1-node2"
    c1node2.vm.provider "virtualbox" do |vb|
      # vb.memory = MEMORY
      vb.cpus = "2"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end

  config.vm.define "c1-node3" do |c1node3|
    c1node3.vm.box = "bento/ubuntu-18.04"
    # c1node3.disksize.size = DISK_SIZE
    c1node3.vm.network "private_network", ip: "172.16.94.13"
    c1node3.vm.hostname = "c1-node3"
    c1node3.vm.provider "virtualbox" do |vb|
      # vb.memory = MEMORY
      vb.cpus = "2"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end
 
  config.vm.define "c1-storage", autostart: false do |c1storage|
    c1storage.vm.box = "bento/ubuntu-18.04"
    # c1storage.disksize.size = DISK_SIZE
    c1storage.vm.network "private_network", ip: "172.16.94.5"
    c1storage.vm.hostname = "c1-storage"
    c1storage.vm.provider "virtualbox" do |vb|
      # vb.memory = MEMORY
      vb.cpus = "1"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end
end
